stages:
  - prepare
  - build
  - pack

variables:
  debian_base_image: $CI_REGISTRY_IMAGE/debian_base:latest

.tpl:docker:
  image: reg.git.brickburg.de/bbcontainers/hub/docker:stable
  tags:
    - docker

.tpl:stable:
  extends: .tpl:docker
  only:
    - master

.tpl:defaultalpinebuild:
  stage: build
  extends: .tpl:stable
  parallel:
    matrix:
      - ARCH: 'amd64'
        BASEIMAGE: reg.git.brickburg.de/bbcontainers/hub/alpine:3
      - ARCH: 'aarch64'
        BASEIMAGE: reg.git.brickburg.de/bbcontainers/hub/arm64v8/alpine:3
      - ARCH: 'armv7'
        BASEIMAGE: reg.git.brickburg.de/bbcontainers/hub/arm32v7/alpine:3
  script:
    # build
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - cd src/$containerfolder
    - docker build -t "$uidimage" --build-arg ARCH=$ARCH --build-arg BASEIMAGE=$BASEIMAGE .
    - cd ../../
    # extract binary
    - docker run -d --rm --name "$uidname" "$uidimage" /bin/sleep 300
    - sleep 3
    - docker cp $uidname:/dist .
    - docker stop $uidname
    - sleep 3
    - docker image rm "$uidimage"
  artifacts:
    paths:
      - dist/
  variables:
    uidimage: "staticbuild_${CI_JOB_ID}:latest"
    uidname: "staticbuild_${CI_JOB_ID}"

prepare:debian-base:
  stage: prepare
  extends: .tpl:stable
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - cd src/debian-base
    - docker build -t "$debian_base_image" .
    - docker push $CI_REGISTRY_IMAGE/debian_base:latest

build:busybox:
  stage: build
  extends: .tpl:stable
  parallel:
    matrix:
      - compiler: '.'
        arch: '.'
        name: '86_64'
      - compiler: 'aarch64-linux-gnu-'
        arch: 'aarch64'
        name: aarch64
      - compiler: 'arm-linux-gnueabi-'
        arch: 'arm'
        name: 'arm'
  script:
    # build
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - cd src/busybox
    - if [ "$compiler" == "." ]; then compiler=""; fi
    - if [ "$arch" == "." ]; then arch=""; fi
    - docker build -t "$uidimage" --build-arg BASEIMAGE=$debian_base_image --build-arg CROSS_COMPILE=$compiler --build-arg ARCH=$arch --build-arg NAME=$name .
    - cd ../../
    # extract binary
    - docker run -d --rm --name "$uidname" "$uidimage" /bin/sleep 300
    - sleep 3
    - docker cp $uidname:/dist .
    - docker stop $uidname
    - sleep 3
    - docker image rm "$uidimage"
  artifacts:
    paths:
      - dist/
  variables:
    uidimage: "staticbuild_${CI_JOB_ID}:latest"
    uidname: "staticbuild_${CI_JOB_ID}"

build:tcpdump:
  stage: build
  extends: .tpl:defaultalpinebuild
  variables:
    containerfolder: tcpdump

build:curl:
  stage: build
  extends: .tpl:defaultalpinebuild
  variables:
    containerfolder: curl

build:vim:
  stage: build
  extends: .tpl:defaultalpinebuild
  variables:
    containerfolder: vim

pack:pack:
  stage: pack
  extends: .tpl:stable
  image: "$debian_base_image"
  script:
    - |
      rm -f dist/info.txt
      while read name
      do
          sha=$(sha512sum $name | awk '{print $1}')
          info=$(file $name | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}')
          bname=$(basename "$name")
          echo -e "name: $bname\nsha512sum: $sha\nfileinfo: $info\n" >> dist/info.txt
      done <<< "$(find dist/ -type f ! -iname meta.txt | sort)"
    - cat dist/info.txt
    - |
      lftp -d --norc <<EOF
      set ftp:ssl-force true
      open -u ${FTP_USER},${FTP_PASSWORD} ftp://${FTP_HOST}
      mirror --reverse --delete-first --delete dist/ $FTP_DIR
      exit
      EOF
  artifacts:
    paths:
      - dist/
