stages:
  - build

build:busybox:
  stage: build
  script:
    # build
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - cd src/busybox
    - docker build -t busybox:latest .
    - cd ../../
    # extract binary
    - docker run -d --rm --name busyboxbuild busybox:latest /bin/sleep infinity
    - sleep 3
    - docker cp busyboxbuild:/dist .
    - docker stop busyboxbuild
  artifacts:
    paths:
      - dist/
  tags:
    - docker
